# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"convert_file_to_json": "00-documentation.ipynb",
         "encode_file_as_utf8": "00-documentation.ipynb",
         "convert_nb_to_md": "00-documentation.ipynb",
         "junix.exporter.convert_file_to_json": "00-documentation.ipynb",
         "MyHTMLParser": "00-documentation.ipynb",
         "convert_df_to_md": "00-documentation.ipynb",
         "remove_empty_index_col": "00-documentation.ipynb",
         "extract_div_to_md_table": "00-documentation.ipynb",
         "extract_div_to_md_tables": "00-documentation.ipynb",
         "clean_md_file_tables": "00-documentation.ipynb",
         "get_substring_idxs": "00-documentation.ipynb",
         "clean_progress_bars": "00-documentation.ipynb",
         "correct_png_name": "00-documentation.ipynb",
         "specify_nb_in_img_fp": "00-documentation.ipynb",
         "get_nb_naive_png_names": "00-documentation.ipynb",
         "get_filename_correction_map": "00-documentation.ipynb",
         "clean_md_text_img_fps": "00-documentation.ipynb",
         "clean_md_files_img_fps": "00-documentation.ipynb",
         "convert_and_clean_nb_to_md": "00-documentation.ipynb",
         "get_field_name_tags": "02-attribute extraction.ipynb",
         "field_hierarchies_to_root": "02-attribute extraction.ipynb",
         "assign_idx_fields": "02-attribute extraction.ipynb",
         "initialise_site_data_with_ids": "02-attribute extraction.ipynb",
         "get_dict_head": "02-attribute extraction.ipynb",
         "datapackage_ref_to_ds_schema": "02-attribute extraction.ipynb",
         "init_datapackage_ref": "02-attribute extraction.ipynb",
         "extract_external_foreignkey_datapackage_refs": "02-attribute extraction.ipynb",
         "add_resource_locs_to_external_datapackage_refs": "02-attribute extraction.ipynb",
         "create_dir": "02-attribute extraction.ipynb",
         "download_attribute_data_to_temp_dir": "02-attribute extraction.ipynb",
         "load_datapackage": "02-attribute extraction.ipynb",
         "load_resource_attr_dfs": "02-attribute extraction.ipynb",
         "load_full_id_map": "02-attribute extraction.ipynb",
         "determine_matched_ids": "02-attribute extraction.ipynb",
         "delete_null_attributes": "02-attribute extraction.ipynb",
         "delete_null_values": "02-attribute extraction.ipynb",
         "extract_attrs_from_resource_dfs": "02-attribute extraction.ipynb",
         "flatten_list": "02-attribute extraction.ipynb",
         "drop_duplicates_attrs": "02-attribute extraction.ipynb",
         "get_dp_field_to_url_format_str": "03-page-population.ipynb",
         "format_id_values": "03-page-population.ipynb",
         "single_site_data_to_ids_df": "03-page-population.ipynb",
         "single_site_data_to_ids_md_str": "03-page-population.ipynb",
         "attrs_df_to_md_str": "03-page-population.ipynb",
         "format_attribute_value_types": "03-page-population.ipynb",
         "get_datapackage_url_to_attributes": "03-page-population.ipynb",
         "get_datapackage_url_to_attrs_md_str": "03-page-population.ipynb",
         "filter_dict": "03-page-population.ipynb",
         "construct_dataset_md_str": "03-page-population.ipynb",
         "single_site_data_to_datasets_md_str": "03-page-population.ipynb",
         "clean_dp_name": "03-page-population.ipynb",
         "extract_name_from_single_site_data": "03-page-population.ipynb",
         "single_site_data_to_md_str": "03-page-population.ipynb",
         "populate_and_save_template": "03-page-population.ipynb",
         "clean_object_names": "03-page-population.ipynb"}

modules = ["dev/docs.py",
           "extraction.py",
           "population.py"]

doc_url = "https://OSUKED.github.io/Power-Station-Dictionary/"

git_url = "https://github.com/OSUKED/Power-Station-Dictionary"

def custom_doc_links(name): return None
