# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"retrieve_opsd_power_plants_page": "01-source-data.ipynb",
         "extract_EU_power_plants_csv_url": "01-source-data.ipynb",
         "download_opsd_power_plants_data": "01-source-data.ipynb",
         "load_source_definitions": "03-database-construction.ipynb",
         "identify_primary_keys": "03-database-construction.ipynb",
         "check_source_for_disallowed_cols": "03-database-construction.ipynb",
         "check_sources_for_disallowed_cols": "03-database-construction.ipynb",
         "identify_inputs_for_output_cols": "03-database-construction.ipynb",
         "get_input_key_to_attr": "03-database-construction.ipynb",
         "get_primary_key_to_attr": "03-database-construction.ipynb",
         "update_df_col": "03-database-construction.ipynb",
         "add_attr_cols": "03-database-construction.ipynb",
         "add_key_cols": "03-database-construction.ipynb",
         "construct_output_df": "03-database-construction.ipynb",
         "filter_cols_for_one_to_many": "04-updates-and-cleaning.ipynb",
         "apply_updates": "04-updates-and-cleaning.ipynb",
         "check_output_col_values": "04-updates-and-cleaning.ipynb",
         "apply_output_col_types": "04-updates-and-cleaning.ipynb",
         "check_and_apply_output_defs": "04-updates-and-cleaning.ipynb",
         "download_source_data": "05-pipeline.ipynb",
         "construct_intermediate_dataset": "05-pipeline.ipynb",
         "update_dataset_updates": "05-pipeline.ipynb",
         "clean_output_dataset": "05-pipeline.ipynb",
         "save_output_dataset": "05-pipeline.ipynb",
         "generate_output_dataset_pipeline": "05-pipeline.ipynb"}

modules = ["download.py",
           "construct.py",
           "update.py",
           "pipeline.py"]

doc_url = "https://OSUKED.github.io/Power-Station-Dictionary/"

git_url = "https://github.com/OSUKED/Power-Station-Dictionary"

def custom_doc_links(name): return None
